### ISSUE TITLE
Fail to delete policy

### ISSUE THREAD

**Issue by takuyateraoka** [Azure-Samples/active-directory-b2c-graph-trustframework-policy#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
B2CPolicyClient delete "policy name"

### Any log messages given by the failure
>
DELETE https://graph.microsoft.com/beta/trustFramework/policies/B2C_1A_signup_signin2/$value

Error Calling the Graph API HTTP Status=NotFound
Transfer-Encoding: chunked
request-id: 9306b0b6-a9cb-4e46-9f07-e5a7fc5bfcb6
client-request-id: 9306b0b6-a9cb-4e46-9f07-e5a7fc5bfcb6
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Japan East","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_4","ADSiteName":"JPE"}}
Duration: 405.2022
Strict-Transport-Security: max-age=31536000
Cache-Control: private
Date: Mon, 15 Apr 2019 01:47:21 GMT

{
  "error": {
    "code": "UnknownError",
    "message": "<Error><Message>No HTTP resource was found that matches the request URI 'https://cpim.windows.net/graph/trustFramework/policies('B2C_1A_signup_signin2')/$value'.</Message><MessageDetail>No action was found on the controller 'TrustFramework' that matches the request.</MessageDetail><StackTrace /></Error>",
    "innerError": {
      "request-id": "9306b0b6-a9cb-4e46-9f07-e5a7fc5bfcb6",
      "date": "2019-04-15T01:47:22"
    }
  }
}

### Expected/desired behavior
>
Successfully removed

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows10

### Versions
>

### Mention any other details that might be useful
It was necessary for the deletion of custom policy to use "https://graph.microsoft.com/beta/trustFramework/policies/{0}".
It is not "https://graph.microsoft.com/beta/trustFramework/policies/{0}/$value".

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by agrabhi** [comment]
Thanks for raising the issue. $value is an OData construct which is used to read a raw value/stream resource or a blob resource. 
https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/using-select-expand-and-value#getting-individual-properties-of-an-entity-value

So for delete, you have to still call  "https://graph.microsoft.com/beta/trustFramework/policies/{0}".
